### ISSUE TITLE
EMISSIVE_MODE=2 信标光束变黑

### ISSUE THREAD

**Issue by OrzMiku** [HaringPro/Revelation#10]
```
环境：iris 1.8 beta4
游戏版本：1.21.1
```

EMISSIVE_MODE=2 信标光束变黑
![image](https://github.com/user-attachments/assets/4e908e0d-86b0-42c6-862e-0600be026914)
NORMAL_MAPPING=true 光束完全变黑
![image](https://github.com/user-attachments/assets/3ad26d7a-5d30-4ae5-b031-fec58310f9b6)

**Comment by HaringPro** [comment]
already fixed

**Comment by OrzMiku** [comment]
![image](https://github.com/user-attachments/assets/65d6ae6f-a423-431d-ab57-e97162e4ba68)
问题依然存在
